name: Lint

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.11.1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: reviewdog/action-eslint@v1
        with:
          fail_on_error: true
          eslint_flags: "."
